"""Workflow for generating PROJECT_AGENT_MANUAL.md."""

from datetime import datetime
from pathlib import Path
from typing import Any

from project_memory_mcp.db.connection import get_session
from project_memory_mcp.db.models import Equation, File, Symbol


class GenerateManualWorkflow:
    """
    Workflow for generating PROJECT_AGENT_MANUAL.md.

    Generates a comprehensive usage manual for the project's knowledge graph,
    tailored to the specific codebase.
    """

    DEFAULT_MANUAL_TEMPLATE = """# PROJECT AGENT MANUAL — {project_name}

> Generated by Project Memory MCP on {date}

## Purpose of This Manual

This manual is your guide to understanding and working with this codebase. 
Use it in conjunction with the Project Memory MCP tools to query, modify, and maintain this project safely.

---

## 1. Project Overview

{project_overview}

### Core Files

{core_files}

### Architecture Summary

{architecture_summary}

---

## 2. How to Query the Project

### Query Files

{query_files_info}

### Query Symbols

{query_symbols_info}

### Query Equations

{query_equations_info}

---

## 3. Safety Checks

### Before Modifying

{safety_modify_info}

### Before Deleting

{safety_delete_info}

---

## 4. After Making Changes

{after_changes_info}

---

## 5. Recommended Query Patterns

{recommended_queries}

---

## 6. Critical Regions

{critical_regions}

---

## 7. Risk Overview

{risk_overview}

---

*Manual last updated: {date}*
"""

    def __init__(self, project_path: str, config: dict[str, Any] | None = None):
        self.project_path = Path(project_path).resolve()
        self.config = config or {}
        self.memory_dir = self.project_path / ".project-memory"

    async def execute(self) -> dict[str, Any]:
        """Generate the PROJECT_AGENT_MANUAL.md file."""
        await self._ensure_memory_dir()

        # Collect data from database
        data = await self._collect_manual_data()

        # Generate content
        content = self._generate_content(data)

        # Write to file
        manual_path = self._write_manual(content)

        # Store manual entries in database
        await self._store_manual_entries(data)

        return {
            "generated": True,
            "manual_path": str(manual_path),
            "sections": 7,
            "content": content,
        }

    async def _ensure_memory_dir(self) -> None:
        """Ensure the .project-memory directory exists."""
        self.memory_dir.mkdir(parents=True, exist_ok=True)

    async def _collect_manual_data(self) -> dict[str, Any]:
        """Collect data from the database for manual generation."""
        from sqlalchemy import select

        data = {
            "project_name": self.project_path.name,
            "date": datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
            "core_files": [],
            "all_files": [],
            "symbols": [],
            "equations": [],
            "risks": [],
        }

        async with get_session() as session:
            # Get core files
            stmt = select(File).where(File.is_core == True).limit(10)
            result = await session.execute(stmt)
            core_files = result.scalars().all()
            for f in core_files:
                data["core_files"].append({
                    "path": f.path,
                    "purpose": f.purpose or "Unknown",
                    "summary": f.llm_summary or "",
                })

            # Get all files with analysis
            stmt = select(File).where(
                (File.is_source == True) &
                (File.analysis_status == "completed")
            ).order_by(File.path).limit(50)
            result = await session.execute(stmt)
            all_files = result.scalars().all()
            data["all_files"] = [{
                "path": f.path,
                "language": f.language,
                "purpose": f.purpose or "Unknown",
                "is_core": f.is_core,
                "is_entrypoint": f.is_entrypoint,
            } for f in all_files]

            # Get symbols
            stmt = select(Symbol).where(
                Symbol.symbol_type.in_(["function", "method", "class"]) &
                (Symbol.confidence >= 0.5)
            ).limit(100)
            result = await session.execute(stmt)
            symbols = result.scalars().all()
            data["symbols"] = [{
                "name": s.name,
                "qualified_name": s.qualified_name,
                "type": s.symbol_type,
                "responsibility": s.responsibility or "",
            } for s in symbols]

            # Get equations
            stmt = select(Equation).limit(50)
            result = await session.execute(stmt)
            equations = result.scalars().all()
            data["equations"] = [{
                "name": e.name or f"eq_{e.id}",
                "type": e.equation_type,
                "mathematical_meaning": e.mathematical_meaning or "",
            } for e in equations]

        return data

    def _generate_content(self, data: dict[str, Any]) -> str:
        """Generate the manual content."""
        project_name = data["project_name"]
        date = data["date"]

        # Project overview
        project_overview = self._generate_overview(data)

        # Core files section
        core_files = self._generate_core_files_section(data)

        # Architecture summary
        architecture_summary = self._generate_architecture_summary(data)

        # Query sections
        query_files_info = self._generate_query_files_info(data)
        query_symbols_info = self._generate_query_symbols_info(data)
        query_equations_info = self._generate_query_equations_info(data)

        # Safety sections
        safety_modify_info = self._generate_safety_modify_info()
        safety_delete_info = self._generate_safety_delete_info()

        # After changes
        after_changes_info = self._generate_after_changes_info()

        # Recommended queries
        recommended_queries = self._generate_recommended_queries(data)

        # Critical regions and risk
        critical_regions = self._generate_critical_regions(data)
        risk_overview = self._generate_risk_overview(data)

        # Format the template
        content = self.DEFAULT_MANUAL_TEMPLATE.format(
            project_name=project_name,
            date=date,
            project_overview=project_overview,
            core_files=core_files,
            architecture_summary=architecture_summary,
            query_files_info=query_files_info,
            query_symbols_info=query_symbols_info,
            query_equations_info=query_equations_info,
            safety_modify_info=safety_modify_info,
            safety_delete_info=safety_delete_info,
            after_changes_info=after_changes_info,
            recommended_queries=recommended_queries,
            critical_regions=critical_regions,
            risk_overview=risk_overview,
        )

        return content

    def _generate_overview(self, data: dict[str, Any]) -> str:
        """Generate project overview."""
        return f"""This is the knowledge graph manual for **{data['project_name']}**.

The project contains {len(data['all_files'])} analyzed source files, 
{len(data['symbols'])} functions/classes/methods, 
and {len(data['equations'])} identified equations.

Use the query tools described below to navigate and understand this codebase."""

    def _generate_core_files_section(self, data: dict[str, Any]) -> str:
        """Generate core files section."""
        if not data["core_files"]:
            return "No core files identified yet."

        lines = []
        for f in data["core_files"]:
            lines.append(f"- **{f['path']}**: {f['purpose']}")
            if f["summary"]:
                lines.append(f"  - {f['summary']}")
        return "\n".join(lines)

    def _generate_architecture_summary(self, data: dict[str, Any]) -> str:
        """Generate architecture summary."""
        return """The project architecture can be queried via:
- `project.query_file(file_path="...")` for file details
- `project.query_symbol(symbol_name="...")` for function/class details
- `project.query_equation(keyword="...")` for equation details
- `project.search_graph(query="...")` for general search"""

    def _generate_query_files_info(self, data: dict[str, Any]) -> str:
        """Generate file query information."""
        return """To query information about a specific file:

```
project.query_file(file_path="path/to/file.py")
```

This returns:
- File purpose, language, role (core/entrypoint/test)
- All symbols (functions, classes, methods) defined in the file
- All equations detected in the file
- Import dependencies"""

    def _generate_query_symbols_info(self, data: dict[str, Any]) -> str:
        """Generate symbol query information."""
        return """To query information about a specific function, class, or method:

```
project.query_symbol(symbol_name="function_name")
```

This returns:
- Symbol definition, signature, docstring
- Callers (what calls this symbol)
- Callees (what this symbol calls)
- Equations used by this symbol
- LLM analysis: responsibility, side effects, complexity"""

    def _generate_query_equations_info(self, data: dict[str, Any]) -> str:
        """Generate equation query information."""
        return """To query equations in the codebase:

```
project.query_equation(keyword="loss")
project.query_equation(keyword="PID")
```

This returns:
- Equation type (control, loss, matrix, optimization, etc.)
- Mathematical meaning and physical interpretation
- Input/output variables
- Algorithmic role
- Related symbols and files"""

    def _generate_safety_modify_info(self, data: dict[str, Any]) -> str:
        """Generate safety info for modification."""
        return """**Before modifying any file, symbol, or equation:**

1. Run impact analysis:
   ```
   project.query_impact(
     target_type="equation",
     target_name="loss",
     operation_type="modify"
   )
   ```

2. Review the affected files, symbols, and risk assessment

3. Create an edit proposal:
   ```
   project.propose_edit(file_path="...", changes=[...], reason="...")
   ```

4. After confirmation, apply the edit:
   ```
   project.apply_edit(file_path="...", changes=[...], confirm=true)
   ```

5. Rescan changed files:
   ```
   project.rescan_changed_files(project_path=".")
   ```"""

    def _generate_safety_delete_info(self, data: dict[str, Any]) -> str:
        """Generate safety info for deletion."""
        return """**Before deleting any file, symbol, or equation:**

1. Check delete safety:
   ```
   project.delete_candidate(
     target_type="file",
     target_name="old_module.py",
     target_path="src/old_module.py"
   )
   ```

2. Review references, dependents, and orphaned code

3. Only after explicit confirmation:
   ```
   project.confirm_delete(
     target_type="file",
     target_name="old_module.py",
     target_path="src/old_module.py",
     confirmed=true
   )
   ```

**WARNING:** Never call `project.confirm_delete` with `confirmed=true` without first running `project.delete_candidate` and reviewing the results."""

    def _generate_after_changes_info(self, data: dict[str, Any]) -> str:
        """Generate post-change info."""
        return """After making changes:

1. Rescan the project:
   ```
   project.rescan_changed_files(project_path=".")
   ```

2. Regenerate the manual:
   ```
   project.generate_manual(project_path=".")
   ```

3. Update the LLM analysis for changed entities (the server will create new analysis tasks)"""

    def _generate_recommended_queries(self, data: dict[str, Any]) -> str:
        """Generate recommended queries."""
        queries = []

        # Based on the project, suggest useful queries
        if data["equations"]:
            eq_types = set(e["type"] for e in data["equations"])
            if "control" in eq_types:
                queries.append("- Query control equations: `project.query_equation(keyword=\"control\", equation_type=\"control\")`")
            if "loss" in eq_types:
                queries.append("- Query loss functions: `project.query_equation(keyword=\"loss\", equation_type=\"loss\")`")

        if data["symbols"]:
            queries.append("- Explore symbol responsibilities: `project.query_symbol(symbol_name=\"...\")`")

        queries.append("- Search the entire graph: `project.search_graph(query=\"...\")`")
        queries.append("- List all core files: Use `project.search_graph(query=\"core\")` with entity_types=[\"file\"]")

        return "\n".join(queries) if queries else "No specific recommendations yet."

    def _generate_critical_regions(self, data: dict[str, Any]) -> str:
        """Generate critical regions info."""
        critical = []
        for f in data["all_files"]:
            if f.get("is_core") or f.get("is_entrypoint"):
                critical.append(f"- **{f['path']}** ({f.get('purpose', 'Unknown')})")

        return "\n".join(critical) if critical else "No critical regions identified yet."

    def _generate_risk_overview(self, data: dict[str, Any]) -> str:
        """Generate risk overview."""
        return """Risk assessment is based on:
- Coupling: How many other files/symbols depend on an entity
- Complexity: How complex the logic is
- Test coverage: Whether tests exist for the entity

Use `project.query_impact(target_type="file", target_name="...", operation_type="modify")` to get detailed risk assessment for any entity."""

    def _write_manual(self, content: str) -> Path:
        """Write the manual to file."""
        manual_path = self.memory_dir / "PROJECT_AGENT_MANUAL.md"
        with open(manual_path, "w", encoding="utf-8") as f:
            f.write(content)
        return manual_path

    async def _store_manual_entries(self, data: dict[str, Any]) -> None:
        """Store manual entries in database."""
        from sqlalchemy import delete

        async with get_session() as session:
            # Clear old entries
            from project_memory_mcp.db.models import ManualEntry
            await session.execute(delete(ManualEntry))

            # Create new entries
            entries = [
                ManualEntry(section="overview", title="Project Overview", content=self._generate_overview(data), order=1),
                ManualEntry(section="query", title="Querying Files", content=self._generate_query_files_info(data), order=2),
                ManualEntry(section="query", title="Querying Symbols", content=self._generate_query_symbols_info(data), order=3),
                ManualEntry(section="query", title="Querying Equations", content=self._generate_query_equations_info(data), order=4),
                ManualEntry(section="safety", title="Before Modifying", content=self._generate_safety_modify_info(data), order=5),
                ManualEntry(section="safety", title="Before Deleting", content=self._generate_safety_delete_info(data), order=6),
                ManualEntry(section="recommendations", title="Recommended Queries", content=self._generate_recommended_queries(data), order=7),
            ]

            for entry in entries:
                session.add(entry)


async def generate_manual(project_path: str) -> dict[str, Any]:
    """Convenience function to generate the manual."""
    workflow = GenerateManualWorkflow(project_path)
    return await workflow.execute()
